const tokens = {
  "bg-main": "bg0",
  "bg-outer": "bg1",
  "bg-inner": "bg2",
  "bg-button": "bg4",
  "text": "fg",
  "text-hover": "bg4",
  "shadow": "bg1",
  "timer-track": "bg3",
} as const;

const accents = [
  "red",
  "orange",
  "yellow",
  "green",
  "aqua",
  "blue",
  "purple",
] as const;

const defaultAccent = "orange";

export const gruvbox = {
  defaultMode: "dark",
  modes: {
    dark: {
      defaultFlavor: "medium",
      flavors: {
        hard: {
          colors: {
            bg0: "#1d2021",
            bg1: "#3c3836",
            bg2: "#504945",
            bg3: "#665c54",
            bg4: "#7c6f64",
            fg: "#ebdbb2",
            red: "#fb4934",
            orange: "#fe8019",
            yellow: "#fabd2f",
            green: "#b8bb26",
            aqua: "#8ec07c",
            blue: "#83a598",
            purple: "#d3869b",
          },
          tokens,
          accents,
          defaultAccent,
        },
        medium: {
          colors: {
            bg0: "#282828",
            bg1: "#3c3836",
            bg2: "#504945",
            bg3: "#665c54",
            bg4: "#7c6f64",
            fg: "#ebdbb2",
            red: "#fb4934",
            orange: "#fe8019",
            yellow: "#fabd2f",
            green: "#b8bb26",
            aqua: "#8ec07c",
            blue: "#83a598",
            purple: "#d3869b",
          },
          tokens,
          accents,
          defaultAccent,
        },
        soft: {
          colors: {
            bg0: "#32302f",
            bg1: "#3c3836",
            bg2: "#504945",
            bg3: "#665c54",
            bg4: "#7c6f64",
            fg: "#ebdbb2",
            red: "#fb4934",
            orange: "#fe8019",
            yellow: "#fabd2f",
            green: "#b8bb26",
            aqua: "#8ec07c",
            blue: "#83a598",
            purple: "#d3869b",
          },
          tokens,
          accents,
          defaultAccent,
        },
      },
    },
    light: {
      defaultFlavor: "medium",
      flavors: {
        hard: {
          colors: {
            bg0: "#f9f5d7",
            bg1: "#ebdbb2",
            bg2: "#d5c4a1",
            bg3: "#bdae93",
            bg4: "#a89984",
            fg: "#3c3836",
            red: "#9d0006",
            orange: "#af3a03",
            yellow: "#b57614",
            green: "#79740e",
            aqua: "#427b58",
            blue: "#076678",
            purple: "#8f3f71",
          },
          tokens,
          accents,
          defaultAccent,
        },
        medium: {
          colors: {
            bg0: "#fbf1c7",
            bg1: "#ebdbb2",
            bg2: "#d5c4a1",
            bg3: "#bdae93",
            bg4: "#a89984",
            fg: "#3c3836",
            red: "#9d0006",
            orange: "#af3a03",
            yellow: "#b57614",
            green: "#79740e",
            aqua: "#427b58",
            blue: "#076678",
            purple: "#8f3f71",
          },
          tokens,
          accents,
          defaultAccent,
        },
        soft: {
          colors: {
            bg0: "#f2e5bc",
            bg1: "#ebdbb2",
            bg2: "#d5c4a1",
            bg3: "#bdae93",
            bg4: "#a89984",
            fg: "#3c3836",
            red: "#9d0006",
            orange: "#af3a03",
            yellow: "#b57614",
            green: "#79740e",
            aqua: "#427b58",
            blue: "#076678",
            purple: "#8f3f71",
          },
          tokens,
          accents,
          defaultAccent,
        },
      },
    },
  },
} as const;
